SELECT * 
FROM
    (SELECT 
            REST_ID
        ,	REST_NAME
        ,	FOOD_TYPE
        ,	FAVORITES
        ,	ADDRESS
        ,	ROUND((SELECT AVG(REVIEW_SCORE) FROM REST_REVIEW B WHERE B.REST_ID=A.REST_ID),2) AS SCORE
    FROM REST_INFO A 
    WHERE ADDRESS LIKE '서울%')
WHERE SCORE IS NOT NULL
ORDER BY SCORE DESC,FAVORITES DESC