-- 어느 자동차 대여 회사의 자동차 대여 기록 정보를 담은 CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- https://school.programmers.co.kr/learn/courses/30/lessons/151139
SELECT TO_NUMBER(TO_CHAR(START_DATE,'MM')) MONTH
     , CAR_ID
     , COUNT(CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
        GROUP BY CAR_ID HAVING COUNT(CAR_ID)>=5)
AND TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
GROUP BY TO_NUMBER(TO_CHAR(START_DATE,'MM')), CAR_ID  
ORDER BY MONTH, CAR_ID DESC

