-- 어느 자동차 대여 회사에서 대여 중인 자동차들의 정보를 담은 CAR_RENTAL_COMPANY_CAR
-- 자동차 대여 기록 정보를 담은 CAR_RENTAL_COMPANY_RENTAL_HISTORY
SELECT
    DISTINCT A.CAR_ID
FROM
     CAR_RENTAL_COMPANY_CAR A
   , CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE 
     A.CAR_ID=B.CAR_ID
 AND A.CAR_TYPE='세단'
 AND TO_CHAR(B.START_DATE,'YYYYMM') ='202210'
ORDER BY
   A.CAR_ID DESC
    
