-- 어느 의류 쇼핑몰에 가입한 회원 정보를 담은 USER_INFO
-- 온라인 상품 판매 정보를 담은 ONLINE_SALE
-- 상품을 구매한 회원수, 상품을 구매한 회원수 비율
SELECT TOT1.YEAR
     , TOT1.MONTH
     , TOT1.PUCHASED_USERS
     , ROUND(TOT1.PUCHASED_USERS/TOT2.USER_TOT,'1') PUCHASED_RATIO
FROM
    (SELECT TO_CHAR(A.SALES_DATE,'YYYY') YEAR
          , TO_NUMBER(TO_CHAR(A.SALES_DATE,'MM')) MONTH
          , COUNT(DISTINCT A.USER_ID) PUCHASED_USERS
     FROM ONLINE_SALE A, USER_INFO B
     WHERE A.USER_ID=B.USER_ID 
       AND TO_CHAR(B.JOINED,'YYYY')='2021'
     GROUP BY TO_CHAR(SALES_DATE,'YYYY')
            , TO_NUMBER(TO_CHAR(SALES_DATE,'MM'))) TOT1,
    (SELECT COUNT(1) USER_TOT FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY')='2021') TOT2
ORDER BY YEAR, MONTH
