-- 식품의 정보를 담은 FOOD_PRODUCT 
SELECT 
        B.*
      , A.PRODUCT_NAME 
FROM FOOD_PRODUCT A
    ,(SELECT CATEGORY         
          ,  MAX(PRICE) MAX_PRICE  
      FROM FOOD_PRODUCT 
      WHERE CATEGORY IN ('과자','국','김치','식용유')
      GROUP BY CATEGORY) B
WHERE A.CATEGORY=B.CATEGORY
  AND A.PRICE=B.MAX_PRICE
ORDER BY B.MAX_PRICE DESC
    