-- https://school.programmers.co.kr/learn/courses/30/lessons/59411
SELECT A.ANIMAL_ID, A.NAME FROM (
SELECT
      B.DATETIME-A.DATETIME DATETIME
    , B.NAME
    , B.ANIMAL_ID
FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID=B.ANIMAL_ID
ORDER BY DATETIME DESC) A
WHERE ROWNUM <3