-- https://school.programmers.co.kr/learn/courses/30/lessons/59412
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) HOUR, COUNT(1) COUNT
FROM ANIMAL_OUTS 
WHERE TO_CHAR(DATETIME,'HH24MM') BETWEEN '08:00' AND '19:59'
GROUP BY TO_CHAR(DATETIME,'HH24')
ORDER BY HOUR