--https://school.programmers.co.kr/learn/courses/30/lessons/151138
SELECT A.HISTORY_ID
     , A.CAR_ID
     , TO_CHAR(A.START_DATE,'YYYY-MM-DD') START_DATE
     , TO_CHAR(A.END_DATE,'YYYY-MM-DD') END_DATE
     , CASE WHEN END_DATE-START_DATE+1>=30 THEN '장기 대여'
       ELSE '단기 대여' END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE TO_CHAR(A.START_DATE,'YYYYMM')='202209'
ORDER BY HISTORY_ID DESC
